import Head from 'next/head';
import Image from 'next/image';

import { useCurrentUser } from '@/hooks/useCurrentUser';

import { handleOAuthClick, signOut } from '@/lib/auth';

import styles from '@/styles/Home.module.css';

export default function Home() {
  const currentUser = useCurrentUser();

  return (
    <>
      <Head>
        <title>Next Starter kit for Keystone6-OAuth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            {currentUser.loading
              ? 'Loading...'
              : currentUser.email || 'Unauthenticated'}
          </p>

          <h1>Next Starter kit for Keystone6-OAuth</h1>
        </div>

        <div style={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          gap: '10px'
        }}>
          {!currentUser.isLoggedIn && (
            <button
              style={{
                backgroundColor: 'blue',
                color: 'white',
                padding: '10px',
                borderRadius: '5px',
                border: 'none',
              }}
              onClick={() => handleOAuthClick('google', '')}
              type="button"
            >
              Login Google
            </button>
          )}

          
          {currentUser.isLoggedIn && (
            <>
              <h2>You are logged in with Google</h2>
              <p>{currentUser.email}</p>
            </>
          )}
          {currentUser.isLoggedIn && (
            <button
              style={{
                backgroundColor: 'blue',
                color: 'white',
                padding: '10px',
                borderRadius: '5px',
                border: 'none',
              }}
              onClick={() => signOut()}
              type="button"
            >
              Logout
            </button>
          )}
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>
      </main>
    </>
  );
}
